"""empty message

Revision ID: 1e4c8a05e2a
Revises: 2e9ce02827d
Create Date: 2014-04-07 15:31:25.134310

"""

# revision identifiers, used by Alembic.
revision = '1e4c8a05e2a'
down_revision = '2e9ce02827d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
