"""empty message

Revision ID: 2e9ce02827d
Revises: 334aefbc10df
Create Date: 2014-04-03 16:28:33.302050

"""

# revision identifiers, used by Alembic.
revision = '2e9ce02827d'
down_revision = '334aefbc10df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packagehistory', sa.Column('pkgarch', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packagehistory', 'pkgarch')
    ### end Alembic commands ###
