"""empty message

Revision ID: 55e8cdb63057
Revises: None
Create Date: 2013-11-29 22:56:14.269560

"""

# revision identifiers, used by Alembic.
revision = '55e8cdb63057'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=10), nullable=True),
    sa.Column('architecture', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('sha')
    )
    op.create_table('nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('node_packages',
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('package_sha', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_name'], ['nodes.name'], ),
    sa.ForeignKeyConstraint(['package_sha'], ['packages.sha'], ),
    )
    op.create_index('idx', 'node_packages', ['node_name', 'package_sha'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx', 'node_packages')
    op.drop_table('node_packages')
    op.drop_table('nodes')
    op.drop_table('packages')
    ### end Alembic commands ###
