"""empty message

Revision ID: 1444ba317b65
Revises: None
Create Date: 2013-11-25 10:32:40.678287

"""

# revision identifiers, used by Alembic.
revision = '1444ba317b65'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('packages',
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=10), nullable=True),
    sa.Column('architecture', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('sha'),
    sa.UniqueConstraint('sha')
    )
    op.create_table('node_packages',
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('package_sha', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_name'], ['nodes.name'], ),
    sa.ForeignKeyConstraint(['package_sha'], ['packages.sha'], ),
    sa.PrimaryKeyConstraint('node_name', 'package_sha')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_packages')
    op.drop_table('packages')
    op.drop_table('nodes')
    ### end Alembic commands ###
