"""empty message

Revision ID: 1a3079a206d6
Revises: None
Create Date: 2013-11-20 19:32:13.891276

"""

# revision identifiers, used by Alembic.
revision = '1a3079a206d6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('sha')
    )
    op.create_table('nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_table('packages')
    ### end Alembic commands ###
