"""empty message

Revision ID: 2b36beed66fc
Revises: 1a3079a206d6
Create Date: 2013-11-21 12:13:04.220857

"""

# revision identifiers, used by Alembic.
revision = '2b36beed66fc'
down_revision = '1a3079a206d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_packages',
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('package_sha', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_name'], ['nodes.name'], ),
    sa.ForeignKeyConstraint(['package_sha'], ['packages.sha'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_packages')
    ### end Alembic commands ###
