"""empty message

Revision ID: 45d7de893135
Revises: 2b36beed66fc
Create Date: 2013-11-21 15:53:17.486941

"""

# revision identifiers, used by Alembic.
revision = '45d7de893135'
down_revision = '2b36beed66fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('architecture', sa.String(length=10), nullable=True))
    op.add_column('packages', sa.Column('provider', sa.String(length=10), nullable=True))
    op.add_column('packages', sa.Column('summary', sa.String(length=255), nullable=True))
    op.add_column('packages', sa.Column('uri', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'uri')
    op.drop_column('packages', 'summary')
    op.drop_column('packages', 'provider')
    op.drop_column('packages', 'architecture')
    ### end Alembic commands ###
